[package]
name = "SocketControllerRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mouse-keyboard-input = { git = "https://github.com/positiveway/mouse-keyboard-input", branch = "main" }